services:
  - type: web
    name: mixpanel-vip
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
